# Generated by Django 5.0 on 2023-12-14 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MP', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctores',
                'db_table': 'doctores',
            },
        ),
        migrations.CreateModel(
            name='turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doctores')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turno',
                'db_table': 'turno',
            },
        ),
    ]
