# Generated by Django 5.0 on 2023-12-15 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_obras_sociales_pacientes_turno_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.obras_sociales'),
        ),
    ]
