# Generated by Django 4.2.8 on 2023-12-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pacientes_obra_social'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctores',
            new_name='doc',
        ),
    ]
