# Generated by Django 4.2.8 on 2023-12-21 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_doctores_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripción', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'enfermedad',
                'verbose_name_plural': 'enfermedades',
                'db_table': 'enfermedad',
            },
        ),
        migrations.AddField(
            model_name='pacientes',
            name='enfermedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enfermedad'),
        ),
    ]
