# Generated by Django 4.2.8 on 2023-12-21 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_enfermedad_pacientes_enfermedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.esp'),
        ),
    ]
