# Generated by Django 4.2.8 on 2023-12-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_turno_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=100, verbose_name='detalle')),
            ],
            options={
                'verbose_name': 'consultorio',
                'verbose_name_plural': 'consultorios',
                'db_table': 'consultorio',
            },
        ),
        migrations.AddField(
            model_name='doc',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.consultorios'),
        ),
    ]
